[package]
name = "check_csk_usb"
version = "0.1.0"
authors = ["MJ <tywf91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.7"
clap = "3.0.0-beta.2"